version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/EcoImpact.API"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/EcoImpact.DataModel"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/EcoImpact.Tests"
    schedule:
      interval: "weekly"