version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecoimpact-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    networks:
      - ecoimpact-net

  ecoimpact-api:
    build:
      context: .
      dockerfile: EcoImpact.API/Dockerfile
    container_name: ecoimpact-api
    ports:
      - "7020:7020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=EcoImpactDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sql
    networks:
      - ecoimpact-net
    
  ecoimpact-frontend:
      build:
      context: .
        dockerfile: EcoImpact.Frontend/Dockerfile
      container_name: ecoimpact-frontend
      ports:
        - "7001:80"
      depends_on:
        - ecoimpact-api
      networks:
        - ecoimpact-net
      environment:
        - ASPNETCORE_ENVIRONMENT=Docker

networks:
  ecoimpact-net:
    driver: bridge