version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecoimpact-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    networks:
      - ecoimpact-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eco", "-d", "EcoImpactDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  ecoimpact-api:
    build:
      context: .
      dockerfile: EcoImpact.API/Dockerfile
    container_name: ecoimpact-api
    ports:
      - "7020:7020"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - JWT=${Jwt}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - ecoimpact-net

  ecoimpact-frontend:
    build:
      context: ./EcoImpact.Frontend
      dockerfile: Dockerfile
    container_name: ecoimpact-frontend
    ports:
      - "7001:80"
    depends_on:
      - ecoimpact-api
    restart: always
    networks:
      - ecoimpact-net
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

networks:
  ecoimpact-net:
    driver: bridge