version: '3.9'

services:
  ecoimpact-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # usar porta 80 interna, 8080 externa
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
