version: '3.8'

services:
  ecoimpact-api:
    image: ecoimpact-api
    build:
      context: .
      dockerfile: EcoImpact.API/Dockerfile
    ports:
      - "7020:7020"
    depends_on:
      - sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=EstaChaveSuperSeguraComPeloMenos32Chars!
      - ConnectionStrings__DefaultConnection=Server=sql;Database=EcoImpactDb;User=sa;Password=MyPass123!

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
