name: CodeQL Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.pdf'
      - '**/*.yml'
  schedule:
    - cron: '0 1 * * 1,5' # segundas e sextas às 01:00 UTC

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual
          config: |
            queries:
              - uses: security-extended

      - name: Restore and Build Solution
        run: |
          dotnet restore EcoImpactSimulator.sln
          dotnet build EcoImpactSimulator.sln --configuration Release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:csharp"
