name: Simulated IAST with ZAP and Coverlet

on:
  push:
    branches: [ resolve-dast ]
  pull_request:
    branches: [ main ]

jobs:
  simulated-iast:
    name: Run Simulated IAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EcoImpactSimulator.sln

      - name: Build API Docker image
        run: docker build -t ecoimpact-api -f EcoImpact.API/Dockerfile .

      - name: Run API container
        run: docker run -d --rm --name ecoimpact-api -p 7020:80 ecoimpact-api

      - name: Wait for API to be up
        run: |
          echo "Esperar 15s para o container arrancar..."
          sleep 15

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-results
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/zap-results:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://localhost:7020 \
              -r zap-report.html \
              -w zap-report.md \
              -J zap-report.json \
              -a \
              --autooff

      - name: Upload ZAP scan results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: zap-results