name: Simulated IAST with ZAP and Coverlet

on:
  push:
    branches: [ resolve-dast ]
  pull_request:
    branches: [ main ]

jobs:
  simulated-iast:
    name: Run Simulated IAST
    runs-on: ubuntu-latest

    services:
      ecoimpact-api:
        image: ghcr.io/joaomonteiro20/ecoimpact-api:latest
        ports:
          - 7020:80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EcoImpactSimulator.sln

      - name: Build API Docker image
        run: docker build -t ecoimpact-api -f EcoImpact.API/Dockerfile .

      - name: Wait for API to be up
        run: |
          echo "Aguarda 15s para o container estar pronto"
          sleep 15

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-results
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/zap-results:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://localhost:7020 \
              -r zap-report.html \
              -w zap-report.md \
              -J zap-report.json \
              -a \
              --autooff \
              --exit-code 0

      - name: Upload ZAP scan results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: zap-results

      - name: Mostrar sumário ZAP
        run: cat zap-results/zap-report.md || echo "Relatório não encontrado"
