name: Simulated DAST with ZAP

on:
  push:
    branches: [resolve-dast]
  pull_request:
    branches: [main]

jobs:
  zap-dast:
    name: Run OWASP ZAP DAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EcoImpactSimulator.sln

      - name: Build solution
        run: dotnet build EcoImpactSimulator.sln --configuration Release --no-restore

      - name: Build Docker image for API
        run: docker build -t ecoimpact-api -f EcoImpact.API/Dockerfile .

      - name: Run API container
        run: |
          docker run -d --name ecoimpact-api -p 7020:80 ecoimpact-api
          echo "Aguardando API subir..."
          sleep 15

      - name: Create results folder
        run: mkdir -p zap-results

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/zap-results:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
              -t http://localhost:7020 \
              -r zap-report.html \
              -w zap-report.md \
              -J zap-report.json \
              -a \
              --autooff

      - name: Upload ZAP results
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: zap-results

      - name: Stop and remove API container
        if: always()
        run: docker stop ecoimpact-api && docker rm ecoimpact-api
