name: SCA - Snyk Scan

on:
  push:
    branches: [ feature-sca ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snyk:
    name: Snyk .NET Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EcoImpactSimulator.sln

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test
