name: SCA - Snyk Vulnerability Scan

on:
  push:
    branches: [feature-sca]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  snyk:
    name: Snyk SCA por projeto
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore EcoImpactSimulator.sln

      - name: Scan API Project
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test EcoImpact.API/EcoImpact.API.csproj --sarif-file-output=snyk-api.sarif

      - name: Scan DataModel Project
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test EcoImpact.DataModel/EcoImpact.DataModel.csproj --sarif-file-output=snyk-datamodel.sarif

      - name: Scan Tests Project
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test EcoImpact.Tests/EcoImpact.Tests.csproj --sarif-file-output=snyk-tests.sarif

      - name: Upload SARIF reports
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-api.sarif

      - name: Upload SARIF reports 2
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-datamodel.sarif

      - name: Upload SARIF reports 3
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-tests.sarif
