name: SCA com Snyk

on:
  workflow_dispatch:
  push:
    branches: [ feature-sca ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore EcoImpactSimulator.sln

      - name: Instalar Snyk CLI
        run: npm install -g snyk

      - name: Autenticar com Snyk
        run: snyk auth "${{ secrets.SNYK_TOKEN }}"

      - name: Scan EcoImpact.API
        run: snyk test --file=EcoImpact.API/EcoImpact.API.csproj --sarif-file-output=snyk-api.sarif

      - name: Fazer upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: snyk-api-report
          path: snyk-api.sarif
